name: Pull Request Build

on:
  workflow_dispatch:


# The `build` and `test` commands ran separately as the Ballerina Gradle plugin does not support skipping test groups
# when the `gradlew build` is used. It is only supported for `gradlew test`.
jobs:
    ubuntu-build:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        concurrency:
          group: ${{ github.head_ref }}-ubuntu-build
          cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 17.0.7

            - name: Set ENV Variables
              run: |
                echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV 

            -   name: Build the Package
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                run: |
                  ./gradlew build -x test ${{ inputs.additional-ubuntu-build-flags }}
                  ./gradlew test ${{ inputs.additional-ubuntu-test-flags }}

            -   name: Generate Codecov Report
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}

    windows-build:
        name: Build on Windows
        runs-on: windows-latest
        concurrency:
          group: ${{ github.head_ref }}-windows-build
          cancel-in-progress: true
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 17.0.7

            - name: Set ENV Variables
              run: |
                echo '${{ toJson(secrets) }}' | pwsh -Command "& { ConvertFrom-Json -InputObject \$input | ForEach-Object { echo ('{0}={1}' -f \$_.Key, \$_.Value) >> \$env:GITHUB_ENV }}"

            -   name: Build the Project
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
                run: |
                  ./gradlew.bat build -x test ${{ inputs.additional-windows-build-flags }}
                  ./gradlew.bat test ${{ inputs.additional-windows-test-flags }}
